import Lecerf.Word.Code
import Mathlib.Algebra.Group.Submonoid.Membership
import Mathlib.Data.PEquiv

/-!
# Morphisms and partial iteration for indexed codes

This file deliberately keeps five map classes apart:

* mathlib's `MonoidHom` is an arbitrary total multiplicative map;
* `InjectiveMorphism` additionally records injectivity;
* `CodeIso` is an intrinsic `MulEquiv` between two generated submonoids and
  records its action on the indexed generators;
* `PaperCodeEpi` reconstructs Lecerf's nonstandard “epimorphism of codes” and
  permits its selector to repeat or omit target generators; and
* `CodeIso.toPEquiv` is the partial action on the ambient free monoid.

The ambient view is semantic and noncomputable because membership in an
arbitrary generated submonoid need not be decidable.  Later finite syntax must
supply its own executable membership procedure.  Partial iterates use literal
`Option.bind`: an undefined intermediate application stays undefined.
-/

namespace Lecerf

namespace Word

universe u v w

variable {A : Type u} {I : Type v} {J : Type w}

/-- The submonoid generated by an indexed family of words. -/
def generated (codewords : I → Word A) : Submonoid (Word A) :=
  Submonoid.closure (Set.range codewords)

/-- A named generator as an element of its generated submonoid. -/
def generator (codewords : I → Word A) (i : I) : generated codewords :=
  ⟨codewords i, Submonoid.subset_closure (Set.mem_range_self i)⟩

@[simp]
theorem generator_coe (codewords : I → Word A) (i : I) :
    (generator codewords i : Word A) = codewords i :=
  rfl

/-- The intrinsic copy of the free monoid on the indices inside the submonoid
generated by an indexed code.  This semantic equivalence uses a classical
inverse of the injective encoding homomorphism. -/
noncomputable def encodingEquiv (codewords : I → Word A)
    (code : IsIndexedCode codewords) : Word I ≃* generated codewords :=
  (MulEquiv.ofLeftInverse' (FreeMonoid.lift codewords)
      (Function.leftInverse_invFun (f := FreeMonoid.lift codewords) code)).trans
    (MulEquiv.submonoidCongr (FreeMonoid.mrange_lift codewords))

@[simp]
theorem encodingEquiv_of (codewords : I → Word A)
    (code : IsIndexedCode codewords) (i : I) :
    encodingEquiv codewords code (FreeMonoid.of i) = generator codewords i := by
  apply Subtype.ext
  change FreeMonoid.lift codewords (FreeMonoid.of i) = codewords i
  exact FreeMonoid.lift_eval_of codewords i

/-- A bundled injective monoid morphism.  This is intentionally weaker than a
`MulEquiv` and stronger than its `toMonoidHom` field. -/
structure InjectiveMorphism (M : Type u) (N : Type v) [Monoid M] [Monoid N] where
  toMonoidHom : M →* N
  injective' : Function.Injective toMonoidHom

namespace InjectiveMorphism

variable {M : Type u} {N : Type v} [Monoid M] [Monoid N]

instance : Coe (InjectiveMorphism M N) (M →* N) :=
  ⟨InjectiveMorphism.toMonoidHom⟩

instance : CoeFun (InjectiveMorphism M N) (fun _ => M → N) :=
  ⟨fun morphism => morphism.toMonoidHom⟩

@[simp]
theorem coe_toMonoidHom (morphism : InjectiveMorphism M N) :
    (morphism.toMonoidHom : M → N) = morphism :=
  rfl

theorem injective (morphism : InjectiveMorphism M N) :
    Function.Injective morphism :=
  morphism.injective'

@[simp]
theorem map_one (morphism : InjectiveMorphism M N) : morphism 1 = 1 :=
  morphism.toMonoidHom.map_one

@[simp]
theorem map_mul (morphism : InjectiveMorphism M N) (x y : M) :
    morphism (x * y) = morphism x * morphism y :=
  morphism.toMonoidHom.map_mul x y

end InjectiveMorphism

/-- An isomorphism of indexed codes is intrinsically an equivalence between
the submonoids generated by its source and target families.  The final field
rules out arbitrary equivalences that do not respect the displayed generator
correspondence. -/
structure CodeIso (A : Type u) (I : Type v) where
  source : I → Word A
  target : I → Word A
  sourceCode : IsIndexedCode source
  targetCode : IsIndexedCode target
  toMulEquiv : generated source ≃* generated target
  map_generator : ∀ i, toMulEquiv (generator source i) = generator target i

namespace CodeIso

variable (iso : CodeIso A I)

/-- Matching two indexed codes generator-by-generator canonically induces a
code isomorphism.  Callers do not need to manufacture the intrinsic
submonoid equivalence. -/
noncomputable def ofCodes (source target : I → Word A)
    (sourceCode : IsIndexedCode source) (targetCode : IsIndexedCode target) :
    CodeIso A I where
  source := source
  target := target
  sourceCode := sourceCode
  targetCode := targetCode
  toMulEquiv := (encodingEquiv source sourceCode).symm.trans
    (encodingEquiv target targetCode)
  map_generator i := by
    change (encodingEquiv target targetCode)
      ((encodingEquiv source sourceCode).symm (generator source i)) =
        generator target i
    rw [← encodingEquiv_of source sourceCode i]
    simp only [MulEquiv.symm_apply_apply]
    exact encodingEquiv_of target targetCode i

/-- Forget surjectivity while retaining the intrinsic injective morphism. -/
def toInjectiveMorphism :
    InjectiveMorphism (generated iso.source) (generated iso.target) where
  toMonoidHom := iso.toMulEquiv.toMonoidHom
  injective' := iso.toMulEquiv.injective

/-- The partial action of a code isomorphism on the ambient free monoid.

It is defined exactly on `generated iso.source`; its inverse is defined
exactly on `generated iso.target`.  Classical membership decisions make this
a semantic, not executable, view. -/
noncomputable def toPEquiv : Word A ≃. Word A := by
  classical
  exact
    { toFun := fun word =>
        if h : word ∈ generated iso.source then
          some (iso.toMulEquiv ⟨word, h⟩).1
        else
          none
      invFun := fun word =>
        if h : word ∈ generated iso.target then
          some (iso.toMulEquiv.symm ⟨word, h⟩).1
        else
          none
      inv := fun sourceWord targetWord => by
        by_cases hs : sourceWord ∈ generated iso.source
        · by_cases ht : targetWord ∈ generated iso.target
          · simp only [hs, ht, dite_true, Option.some.injEq]
            constructor
            · intro inverseEq
              have inverseSubtypeEq :
                  iso.toMulEquiv.symm ⟨targetWord, ht⟩ = ⟨sourceWord, hs⟩ :=
                Subtype.ext inverseEq
              have forwardSubtypeEq := congrArg iso.toMulEquiv inverseSubtypeEq
              exact (congrArg Subtype.val (by simpa using forwardSubtypeEq)).symm
            · intro forwardEq
              have forwardSubtypeEq :
                  iso.toMulEquiv ⟨sourceWord, hs⟩ = ⟨targetWord, ht⟩ :=
                Subtype.ext forwardEq
              have inverseSubtypeEq := congrArg iso.toMulEquiv.symm forwardSubtypeEq
              exact (congrArg Subtype.val (by simpa using inverseSubtypeEq)).symm
          · simp only [hs, ht, dite_true, dite_false, reduceCtorEq]
            constructor
            · intro impossible
              exact impossible.elim
            · intro forwardEq
              apply ht
              rw [← Option.some.inj forwardEq]
              exact (iso.toMulEquiv ⟨sourceWord, hs⟩).2
        · by_cases ht : targetWord ∈ generated iso.target
          · simp only [hs, ht, dite_true, dite_false, reduceCtorEq]
            constructor
            · intro inverseEq
              apply hs
              rw [← Option.some.inj inverseEq]
              exact (iso.toMulEquiv.symm ⟨targetWord, ht⟩).2
            · intro impossible
              exact impossible.elim
          · simp [hs, ht] }

@[simp]
theorem toPEquiv_apply_of_mem (word : Word A)
    (h : word ∈ generated iso.source) :
    iso.toPEquiv word = some (iso.toMulEquiv ⟨word, h⟩).1 := by
  simp [toPEquiv, h]

@[simp]
theorem toPEquiv_apply_of_not_mem (word : Word A)
    (h : word ∉ generated iso.source) : iso.toPEquiv word = none := by
  simp [toPEquiv, h]

@[simp]
theorem toPEquiv_symm_apply_of_mem (word : Word A)
    (h : word ∈ generated iso.target) :
    iso.toPEquiv.symm word = some (iso.toMulEquiv.symm ⟨word, h⟩).1 := by
  change iso.toPEquiv.invFun word = some (iso.toMulEquiv.symm ⟨word, h⟩).1
  simp [toPEquiv, h]

@[simp]
theorem toPEquiv_symm_apply_of_not_mem (word : Word A)
    (h : word ∉ generated iso.target) : iso.toPEquiv.symm word = none := by
  change iso.toPEquiv.invFun word = none
  simp [toPEquiv, h]

theorem toPEquiv_isSome_iff (word : Word A) :
    (iso.toPEquiv word).isSome ↔ word ∈ generated iso.source := by
  classical
  by_cases h : word ∈ generated iso.source <;> simp [h]

theorem toPEquiv_symm_isSome_iff (word : Word A) :
    (iso.toPEquiv.symm word).isSome ↔ word ∈ generated iso.target := by
  classical
  by_cases h : word ∈ generated iso.target <;> simp [h]

@[simp]
theorem toPEquiv_generator (i : I) :
    iso.toPEquiv (iso.source i) = some (iso.target i) := by
  classical
  change iso.toPEquiv (generator iso.source i).1 = some (generator iso.target i).1
  rw [iso.toPEquiv_apply_of_mem _ (generator iso.source i).2]
  exact congrArg (fun word => some word.1) (iso.map_generator i)

@[simp]
theorem toPEquiv_one : iso.toPEquiv 1 = some 1 := by
  classical
  rw [iso.toPEquiv_apply_of_mem 1 (generated iso.source).one_mem]
  simp

theorem toPEquiv_mul_of_mem (left right : Word A)
    (leftMem : left ∈ generated iso.source)
    (rightMem : right ∈ generated iso.source) :
    iso.toPEquiv (left * right) =
      some ((iso.toMulEquiv ⟨left, leftMem⟩).1 *
        (iso.toMulEquiv ⟨right, rightMem⟩).1) := by
  classical
  rw [iso.toPEquiv_apply_of_mem (left * right)
    ((generated iso.source).mul_mem leftMem rightMem)]
  exact congrArg (fun word => some word.1)
    (iso.toMulEquiv.map_mul ⟨left, leftMem⟩ ⟨right, rightMem⟩)

end CodeIso

/-- Lecerf's paper-specific “epimorphism of codes.”

The source and ambient target families are genuine indexed codes.  Relations
send source generator `i` to target generator `selector i`.  No injectivity or
surjectivity hypothesis is imposed on `selector`: selected targets may repeat,
and members of the target code may be omitted. -/
structure PaperCodeEpi (A : Type u) (I : Type v) (J : Type w) where
  source : I → Word A
  target : J → Word A
  selector : I → J
  sourceCode : IsIndexedCode source
  targetCode : IsIndexedCode target
  toMonoidHom : generated source →* generated target
  map_generator : ∀ i,
    toMonoidHom (generator source i) = generator target (selector i)

namespace PaperCodeEpi

/-- Every selector between two indexed codes induces the paper's map class.
The constructor deliberately requires neither selector injectivity nor
selector surjectivity. -/
noncomputable def ofCodes (source : I → Word A) (target : J → Word A)
    (selector : I → J) (sourceCode : IsIndexedCode source)
    (targetCode : IsIndexedCode target) : PaperCodeEpi A I J where
  source := source
  target := target
  selector := selector
  sourceCode := sourceCode
  targetCode := targetCode
  toMonoidHom := (encodingEquiv target targetCode).toMonoidHom.comp
    ((FreeMonoid.map selector).comp (encodingEquiv source sourceCode).symm.toMonoidHom)
  map_generator i := by
    change (encodingEquiv target targetCode)
      (FreeMonoid.map selector
        ((encodingEquiv source sourceCode).symm (generator source i))) =
          generator target (selector i)
    rw [← encodingEquiv_of source sourceCode i]
    simp only [MulEquiv.symm_apply_apply, FreeMonoid.map_of]
    exact encodingEquiv_of target targetCode (selector i)

end PaperCodeEpi

namespace CodeIso

/-- A code isomorphism gives a paper epimorphism with the identity selector,
but the converse need not hold. -/
def toPaperCodeEpi (iso : CodeIso A I) : PaperCodeEpi A I I where
  source := iso.source
  target := iso.target
  selector := id
  sourceCode := iso.sourceCode
  targetCode := iso.targetCode
  toMonoidHom := iso.toMulEquiv.toMonoidHom
  map_generator i := by simpa using iso.map_generator i

end CodeIso

end Word

/-! ## Project-local partial iteration -/

namespace PEquiv

universe u

variable {X : Type u}

/-- Iterate a same-type partial equivalence by partial composition. -/
def iterate (theta : X ≃. X) : Nat → X ≃. X
  | 0 => _root_.PEquiv.refl X
  | n + 1 => (iterate theta n).trans theta

@[simp]
theorem iterate_zero (theta : X ≃. X) :
    iterate theta 0 = _root_.PEquiv.refl X :=
  rfl

@[simp]
theorem iterate_succ (theta : X ≃. X) (n : Nat) :
    iterate theta (n + 1) = (iterate theta n).trans theta :=
  rfl

@[simp]
theorem iterate_zero_apply (theta : X ≃. X) (x : X) :
    iterate theta 0 x = some x :=
  rfl

/-- Successor iteration is literal `Option.bind`; an undefined intermediate
result is not replaced by the input or by a sink value. -/
theorem iterate_succ_apply (theta : X ≃. X) (n : Nat) (x : X) :
    iterate theta (n + 1) x = (iterate theta n x).bind theta :=
  rfl

/-- The same power can be exposed from the left.  This is useful because
inverting a partial composition reverses its displayed order. -/
theorem iterate_succ_left (theta : X ≃. X) (n : Nat) :
    iterate theta (n + 1) = theta.trans (iterate theta n) := by
  induction n with
  | zero => simp
  | succ n inductionHypothesis =>
      calc
        iterate theta ((n + 1) + 1) =
            (iterate theta (n + 1)).trans theta := rfl
        _ = (theta.trans (iterate theta n)).trans theta :=
          congrArg (fun power => power.trans theta) inductionHypothesis
        _ = theta.trans ((iterate theta n).trans theta) :=
          _root_.PEquiv.trans_assoc _ _ _
        _ = theta.trans (iterate theta (n + 1)) := rfl

@[simp]
theorem iterate_one_apply (theta : X ≃. X) (x : X) :
    iterate theta 1 x = theta x := by
  rw [show 1 = 0 + 1 by rfl, iterate_succ_apply]
  rfl

theorem iterate_succ_eq_some_iff (theta : X ≃. X) (n : Nat) (x z : X) :
    iterate theta (n + 1) x = some z ↔
      ∃ y, iterate theta n x = some y ∧ theta y = some z := by
  rw [iterate_succ_apply]
  exact Option.bind_eq_some_iff

theorem iterate_add (theta : X ≃. X) (m n : Nat) :
    iterate theta (m + n) = (iterate theta m).trans (iterate theta n) := by
  induction n with
  | zero => simp
  | succ n inductionHypothesis =>
      rw [Nat.add_succ, iterate_succ, iterate_succ, inductionHypothesis]
      exact _root_.PEquiv.trans_assoc _ _ _

theorem iterate_add_apply (theta : X ≃. X) (m n : Nat) (x : X) :
    iterate theta (m + n) x =
      (iterate theta m x).bind (iterate theta n) := by
  rw [iterate_add]
  rfl

/-- Inverting an iterate is the same as iterating the partial inverse. -/
theorem iterate_symm (theta : X ≃. X) (n : Nat) :
    (iterate theta n).symm = iterate theta.symm n := by
  induction n with
  | zero => rfl
  | succ n inductionHypothesis =>
      rw [iterate_succ, _root_.PEquiv.symm_trans_rev, inductionHypothesis,
        iterate_succ_left]

/-- Exact forward/reverse characterization of an iterated application. -/
theorem iterate_symm_eq_some_iff (theta : X ≃. X) (n : Nat)
    (source target : X) :
    iterate theta.symm n target = some source ↔
      iterate theta n source = some target := by
  rw [← iterate_symm]
  exact (iterate theta n).eq_some_iff

/-- Definedness of a supplied exponent at a supplied input. -/
def DefinedAt (theta : X ≃. X) (n : Nat) (x : X) : Prop :=
  (iterate theta n x).isSome

@[simp]
theorem definedAt_zero (theta : X ≃. X) (x : X) :
    DefinedAt theta 0 x :=
  rfl

theorem definedAt_iff_exists (theta : X ≃. X) (n : Nat) (x : X) :
    DefinedAt theta n x ↔ ∃ z, iterate theta n x = some z := by
  simp [DefinedAt, Option.isSome_iff_exists]

theorem definedAt_succ_iff (theta : X ≃. X) (n : Nat) (x : X) :
    DefinedAt theta (n + 1) x ↔
      ∃ y, iterate theta n x = some y ∧ (theta y).isSome := by
  constructor
  · intro defined
    rcases (definedAt_iff_exists theta (n + 1) x).mp defined with ⟨z, result⟩
    rcases (iterate_succ_eq_some_iff theta n x z).mp result with
      ⟨y, first, second⟩
    exact ⟨y, first, Option.isSome_iff_exists.mpr ⟨z, second⟩⟩
  · rintro ⟨y, first, defined⟩
    rcases Option.isSome_iff_exists.mp defined with ⟨z, second⟩
    exact (definedAt_iff_exists theta (n + 1) x).mpr
      ⟨z, (iterate_succ_eq_some_iff theta n x z).mpr ⟨y, first, second⟩⟩

theorem definedAt_of_definedAt_succ (theta : X ≃. X) (n : Nat) (x : X)
    (defined : DefinedAt theta (n + 1) x) : DefinedAt theta n x := by
  rcases (definedAt_succ_iff theta n x).mp defined with ⟨y, step, _⟩
  exact (definedAt_iff_exists theta n x).mpr ⟨y, step⟩

theorem iterate_add_eq_none_of_eq_none (theta : X ≃. X) (m n : Nat) (x : X)
    (undefined : iterate theta m x = none) :
    iterate theta (m + n) x = none := by
  rw [iterate_add_apply, undefined]
  rfl

/-- The actual partial equivalence at the positive exponent represented by
`k + 1`.  This wrapper prevents a caller from accidentally selecting zero. -/
def positiveIterate (theta : X ≃. X) (k : Nat) : X ≃. X :=
  iterate theta (k + 1)

@[simp]
theorem positiveIterate_apply (theta : X ≃. X) (k : Nat) (x : X) :
    positiveIterate theta k x = (iterate theta k x).bind theta :=
  iterate_succ_apply theta k x

@[simp]
theorem positiveIterate_zero (theta : X ≃. X) :
    positiveIterate theta 0 = theta := by
  ext x
  simp [positiveIterate]

@[simp]
theorem positiveIterate_symm (theta : X ≃. X) (k : Nat) :
    (positiveIterate theta k).symm = positiveIterate theta.symm k :=
  iterate_symm theta (k + 1)

/-- Definedness at the positive exponent represented by `k + 1`. -/
def PositiveDefinedAt (theta : X ≃. X) (k : Nat) (x : X) : Prop :=
  (positiveIterate theta k x).isSome

theorem positiveDefinedAt_iff_exists (theta : X ≃. X) (k : Nat) (x : X) :
    PositiveDefinedAt theta k x ↔
      ∃ z, iterate theta (k + 1) x = some z := by
  simp [PositiveDefinedAt, positiveIterate, Option.isSome_iff_exists]

/-- Some positive iterate is defined at `x`. -/
def PositiveDefined (theta : X ≃. X) (x : X) : Prop :=
  ∃ k, PositiveDefinedAt theta k x

theorem positiveDefined_iff_exists (theta : X ≃. X) (x : X) :
    PositiveDefined theta x ↔
      ∃ k z, iterate theta (k + 1) x = some z := by
  simp only [PositiveDefined, positiveDefinedAt_iff_exists]

/-- A target reached by a fully defined positive iterate. -/
def PositiveIterate (theta : X ≃. X) (source target : X) : Prop :=
  ∃ k, positiveIterate theta k source = some target

theorem positiveIterate_iff_exists_ne_zero (theta : X ≃. X)
    (source target : X) :
    PositiveIterate theta source target ↔
      ∃ n, n ≠ 0 ∧ iterate theta n source = some target := by
  constructor
  · rintro ⟨k, step⟩
    exact ⟨k + 1, Nat.succ_ne_zero k, step⟩
  · rintro ⟨n, nonzero, step⟩
    obtain ⟨k, rfl⟩ := Nat.exists_eq_succ_of_ne_zero nonzero
    exact ⟨k, step⟩

end PEquiv

end Lecerf
